name: Dependabot Check
on: pull_request

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Node Dependencies
        run: yarn

      - name: Build packages
        run: yarn build

      - name: Test packages
        run: yarn test